# This pipeline is triggered upon making a PR against the main branch.
# Unit tests are defined under my_mlops_project/tests
# The integration test deploys and runs the model_training_job defined in my_mlops_project/resources/model-workflow-resource.yml
# This integration test is run in the staging workspace, as defined under my_mlops_project/databricks.yml

# run on merge requests, tags, and the default branch
stages:
  - triggers

image: databricksfieldeng/mlopsstacks:latest

trigger_ci:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/pipelines/my_mlops_project-bundle-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      changes:
        - my_mlops_project/*

trigger_cd_stage:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/pipelines/my_mlops_project-bundle-cd-staging.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

trigger_cd_production:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/pipelines/my_mlops_project-bundle-cd-prod.yml 
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == 'release'