name: Deploy to Staging

on:
  push:
    branches: [main]
    # 移除路径限制，确保任何推送到main都会触发

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    container:
      image: databricksfieldeng/mlopsstacks:latest
    environment: stage
    env:
      DATABRICKS_HOST: "${DATABRICKS_HOST}"
      DATABRICKS_TOKEN: "${DATABRICKS_TOKEN}"
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging
        run: |
          cd my_mlops_project
          databricks bundle validate -t staging
          databricks bundle deploy -t staging
        timeout-minutes: 30